### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by pivnicek** [keboola/sapi-python-client#2]
This thing needs tests.

**Comment by odinuv** [comment]
start with #3 , it's easier then

**Comment by pocin** [comment]
Is `pytest` ok, or you prefer something different?

**Comment by pivnicek** [comment]
`pytest` looks like it would do just fine, thanks for the suggestion!

**Comment by odinuv** [comment]
i would prefere unittest, it's built-in and more similar to junit and phpunit

**Comment by odinuv** [comment]
i did a stub for tests https://github.com/keboola/sapi-python-client/blob/master/tests/test_buckets.py so that they now run automatically against a testing KBC project

**Comment by pocin** [comment]
Guys, is there a way to run tests on local or it's best to make a PR and let Travis do the job?

The tests are failing on local because I don't have ENV variables `KBC_TEST_API_URL` and `KBC_TEST_TOKEN` (i guess).

Also is `python setup.py test` the right way to run them? If so, the `Makefile` I made is useless and I'll delete it.

**Comment by odinuv** [comment]
It is perfectly fine to push to a branch of this repo or PR and Travis will do it. Locally you can set `KBC_TEST_API_URL` to `https://connection.keboola.com` and `KBC_TEST_TOKEN` to some project token - you should have a testing project for this (or we can create it)

**Comment by odinuv** [comment]
yes, i believe makefile is useless

**Comment by pocin** [comment]
@odinuv I've got some issues with the tokens. 
I created a new token (in the UI) just for testing purposes. I didn't give it permissions to any bucket and the tests failed on authorization. This confuses me, because it seems I can't create a buckets without the master token (which I wasn't comfortable giving away). 
Any tips? Or maybe you could supply me with one token for the existing testing project?

**Comment by odinuv** [comment]
y, needs a master token so that it can create buckets, i sent you an invitation to testing project

**Comment by odinuv** [comment]
on second thoughts i made you a fresh devel project, because the tests use static table and bucket names and it's prone to break if they run concurrently

**Comment by odinuv** [comment]
current version: decent test coverage, automated functional and mock tests -> complete
