### ISSUE TITLE
make api_domain optional parameter in Client class

### ISSUE THREAD

**Issue by pocin** [keboola/sapi-python-client#38]
```python
class Client:
    def __init__(self, token, api_domain='https://connection.keboola.com'):
        pass
```

so that you can init the client like this
```python
client = Client('your-token')
```

What are the alternative api_domains anyway?

**Comment by Halama** [comment]
I wouldn't recommend to add default value there, connection URL should be always passed otherwise integration won't wok against other stacks.
At the moment we have two KBC stacks:
 - us-east-1 - https://connection.keboola.com
 - eu-central-1  - https://connection.eu-central-1.keboola.com/ (in BETA now)

eq.  if you are using this client in KBC docker extension you should set api endpoint from `KBC_URL` env variable https://developers.keboola.com/extend/common-interface/environment/#environment-variables

**Comment by pocin** [comment]
Ah okay
